services:


# ——— Основная база (app) ———
  postgres:
    image: postgres:17
    container_name: postgres_pictures
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - "${DB__PORT}:5432"
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_network

    # ——— Тестовая база ———
  postgres_test:
    image: postgres:17
    container_name: postgres_test
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_DB: ${TEST_DB__TEST_NAME}
      POSTGRES_USER: ${TEST_DB__TEST_USER}
      POSTGRES_PASSWORD: ${TEST_DB__TEST_PASSWORD}
    volumes:
      - ./postgres-data_test:/var/lib/postgresql/data
#      - ./initdb/test:/docker-entrypoint-initdb.d
    ports:
      - "${TEST_DB__TEST_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TEST_DB__TEST_USER} -d ${TEST_DB__TEST_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_pictures_app
    env_file:
      - .env.docker-compose
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_network



networks:
  app_network:
    name: app_network
