from typing import Protocol, List

from src.domain.orders.schemas.orders import OrderRead, OrderCreate


class OrderRepositoryProtocol(Protocol):
    async def create_order(self, user_id: int, order: OrderCreate) -> OrderRead: ...

    async def get_order(self, user_id: int, order_id: int) -> OrderRead: ...

    async def list_orders(self, user_id: int) -> List[OrderRead]: ...

    async def update_status(self, order_id: int, status: str) -> None: ...

class OrderServiceProtocol(Protocol):

    async def create_order(self, user_id: int, data: OrderCreate) -> OrderRead: ...

    async def get_order(self, user_id: int, order_id: int) -> OrderRead: ...

    async def list_orders(self, user_id: int) -> list[OrderRead]: ...

    async def update_status(self, order_id: int, status: str) -> None: ...

